### ISSUE TITLE
Ruby bolts (e) against Corporeal Beast is wrong

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#103]
### What went wrong?

Ruby bolts (e) and Ruby dragon bolts (e) proc should hit for the full amount (100 normally, 110 with ZCB). Normal hits are still 50% damage though.

https://dps.osrs.wiki/?id=fb2e4855-a79b-4d03-906c-14aec0218fbc

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/7f06fc6d-f63d-44e0-998f-334a73ac8ad4)

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by Nightfirecat** [comment]
FYI `isWearingCorpbaneWeapon()` still has a `@todo` doc line that can now be removed
