### ISSUE TITLE
Some bolt procs should bypass accuracy check

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#109]
### What went wrong?

Quite a few bolt procs should bypass the accuracy check.
https://oldschool.runescape.wiki/w/Enchanted_bolts#Chances_of_special_effects_occurring
https://twitter.com/JagexAsh/status/1360621821066936324
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/f66e25cc-308f-4ed0-8d7d-463b8a430c2c)

I'm pretty sure this means that for example the ruby bolt (e) proc chance should always be 6% (6.6% with diary).
https://dps.osrs.wiki/?id=19f0f285-3478-49e2-8880-1c79d7c18a91
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/d8e1b2f8-0c30-442c-b98b-2c89abb07fc9)

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
Interesting. I implemented opal and jade as ignoring the accuracy check, although I misread that ruby bolts were not included in that. So it should be just ruby bolts that need fixing.

side note @SuperNerdEric: Thanks a lot for all the testing you've been doing, It's incredibly helpful to have a vigilant set of eyes making sure we polish all the sharp edges, and I really appreciate the thoroughness 😄
