### ISSUE TITLE
Defence-reducing special attacks

### ISSUE THREAD

**Issue by LlemonDuck** [weirdgloop/osrs-dps-calc#110]
### What feature would you like to see?

We do have the defence level x axis on the loadout comparison, and are tracking a feature to add annotations to that chart for certain defence-reducing specials (#37), but we should also provide options to directly specify certain defence-reducing specs in the primary calculation.

Although ordering is applicable, many other tools simply take inputs of how many of each special attack, and apply them in the optimal order: vulnerability/accursed sceptre => dwh => arclight => bgs. This should be sufficient for us as well, and greatly reduces the UI complexity otherwise.

### Calc

- [ ] [Vulnerability](https://oldschool.runescape.wiki/w/Vulnerability): 10%, capped at 10%
    - [ ] Increased to 15% with Tome of water
- [ ] [Accursed sceptre](https://oldschool.runescape.wiki/w/Accursed_sceptre#Uncharged): 15%, capped at 15%
- [ ] [Dragon warhammer](https://oldschool.runescape.wiki/w/Dragon_warhammer): 30%, uncapped
- [ ] [Arclight](https://oldschool.runescape.wiki/w/Arclight): 5% + 1, uncapped
    - [ ] Increased to 10% vs demons
- [ ] [Bandos godsword](https://oldschool.runescape.wiki/w/Bandos_godsword): damage dealt, uncapped

### UI

Due to the number of inputs required, we should fold this under an accordion or some similar method of grouping.

- [ ] [Vulnerability](https://oldschool.runescape.wiki/w/Vulnerability): boolean toggle
- [ ] [Accursed sceptre](https://oldschool.runescape.wiki/w/Accursed_sceptre#Uncharged): boolean toggle
- [ ] [Dragon warhammer](https://oldschool.runescape.wiki/w/Dragon_warhammer): number input of times applied
- [ ] [Arclight](https://oldschool.runescape.wiki/w/Arclight): number input of times applied
- [ ] [Bandos godsword](https://oldschool.runescape.wiki/w/Bandos_godsword): number input of damage dealt

**Comment by SuperNerdEric** [comment]
@LlemonDuck I think the way the Dragon Warhammer defence reduction is currently implemented is slightly off. My assumption is it's actually finding the defence reduction then subtracting that from the original defence level like this:

`def: m.skills.def - Math.trunc(m.skills.def * 3 / 10),`

If you check out the video the Abyssal demon's defence goes from 135 to 95, not 94.
https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/149b720c-915e-42e4-80de-5d15ad2a2bcc

**Comment by LlemonDuck** [comment]
Thanks, I'll update it. Do you mind also testing Arclight to see if it behaves the same? Abyssal demon should work again, it'll be 121 def vs 122 def.

**Comment by SuperNerdEric** [comment]
I got 121. 

That's `135 - Math.trunc(135 * 1 / 10) - 1` right?

https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/ffae1ec8-0c87-4496-939b-7e79da1de9a0

**Comment by LlemonDuck** [comment]
> That's 135 - Math.trunc(135 * 1 / 10) - 1 right?

Yep! Thank you!
