### ISSUE TITLE
Regression: Dharok's/Verac's preset isn't equipping armor

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#113]
### What went wrong?

 Dharok's/Verac's preset isn't equipping armor

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
I think this was introduced in 464de330b5caaf3ad98aee86b83c780e46fcf16e. We were previously pointing to some variants of the barrows gear that was then filtered out.

I'll update the ids for now, but it's something we should keep in mind as we do item filtering. Maybe we can update the template system to find items by name and optional version.

cc @jayktaylor
