### ISSUE TITLE
Pickaxe damage to Guardian (Chambers of Xeric) is incorrect

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#115]
### What went wrong?

Currently the calc just makes the Guardian immune unless you are using a pickaxe. However, damage against Guardians is boosted depending on your mining level and your pickaxe required level.
https://twitter.com/JagexAsh/status/1007600220358742021

https://github.com/weirdgloop/osrs-dps-calc/blob/main/src/lib/CombatCalc.ts#L1275

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
Interesting! I've been wondering about this for years.

**Comment by LlemonDuck** [comment]
I've asked a follow-up on whether this means the crystal pickaxe deals more damage, since it requires 71. I don't believe it does, and I assume the community would have figured it out sooner if it did, so I'll implement it as if it's the same as dragon.

**Comment by LlemonDuck** [comment]
added the initial implementation in 83bd77695e2ce684adbfe9ac3430a22c4d828dff, leaving open until we learn about crystal pickaxe

**Comment by SuperNerdEric** [comment]
> I've asked a follow-up on whether this means the crystal pickaxe deals more damage, since it requires 71. I don't believe it does, and I assume the community would have figured it out sooner if it did, so I'll implement it as if it's the same as dragon.
> 
> https://twitter.com/LlemonDuck/status/1748157271283265693

https://twitter.com/JagexAsh/status/1155820855076802560

**Comment by LlemonDuck** [comment]
Perfect, thanks, Current implementation is correct then.
