### ISSUE TITLE
Gridline ticks should be consistent

### ISSUE THREAD

**Issue by leejt** [weirdgloop/osrs-dps-calc#121]
### What went wrong?

<img width="742" alt="Screenshot 2024-01-20 at 10 29 46 PM" src="https://github.com/weirdgloop/osrs-dps-calc/assets/7573282/cb6dff66-ac6c-425e-ab14-1002c3c86af0">

The grid ticks are not evenly spaced and the spaces between them are fairly arbitrary. I'm not sure what level of control we have over this in the chart library, but if possible we should pick the largest "normal" (1, 2, 5, 10, 20, 50, 100, etc) tick size such that at least (say) 10 are visible on the resulting graph in the x axis, and ~2 are visible in the y axis.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

macOS

**Comment by jayktaylor** [comment]
Improved by https://github.com/weirdgloop/osrs-dps-calc/commit/3a8dded53dd59ef1c6e1161ec5b1a6a1a8ddbb61
