### ISSUE TITLE
TTK graph should use percentages

### ISSUE THREAD

**Issue by leejt** [weirdgloop/osrs-dps-calc#122]
### What went wrong?

<img width="1369" alt="image" src="https://github.com/weirdgloop/osrs-dps-calc/assets/7573282/c9a622a3-3542-4331-89f9-0c0349d04680">

It's not obvious to a layperson that the y axis here is a probability. It should probably be specified as a percentage, and if possible, there should be a "Y-axis" label that is hardcoded to say something like "Probability of killing monster in X ticks"

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

macOS

**Comment by jayktaylor** [comment]
done in https://github.com/weirdgloop/osrs-dps-calc/commit/54f80211fb0b947557ae6d05608253d4b9885329
