### ISSUE TITLE
Dawnbringer applying magic damage bonuses

### ISSUE THREAD

**Issue by jmyaeger** [weirdgloop/osrs-dps-calc#125]
### What went wrong?

The Dawnbringer's max hit is higher than it should be. With 99 magic + imbued heart, the max hit should be floor(109 / 6) - 1 = 17, but it is showing up as 22 in max mage. 

### What did you expect to happen?

The max hit should have been 17 in that case.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

### Any other information

I have not verified this in-game, but the wiki (citing a Mod Ash tweet) claims that magic damage bonuses do not apply to the Dawnbringer's attacks.

**Comment by crab-pancake** [comment]
autoattacks receive bonuses from magic damage, the special attack does not and always rolls 75-150

**Comment by LlemonDuck** [comment]
> autoattacks receive bonuses from magic damage, the special attack does not and always rolls 75-150

No, neither attacks are affected by equipment at all.

**Comment by LlemonDuck** [comment]
closed by 5ff16803ec02b49d9c603844221016b12e74bca5
