### ISSUE TITLE
Scurrius and Rat Bone Weapons

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#130]
### Research Needed
- [x] What is the order of operations between inq and the ratbane bonus?

### Scurrius
- [x] There's a new boss named [Scurrius](https://oldschool.runescape.wiki/w/Scurrius) (meaning the python script needs to be ran)
- [x] You always deal your max hit (100% accuracy) against the [giant rats minions](https://oldschool.runescape.wiki/w/Giant_rat_(Scurrius)) spawned during the boss.

### There's 3 new rat bone weapons:

1.  [Bone mace](https://oldschool.runescape.wiki/w/Bone_mace)
2.  [Bone shortbow](https://oldschool.runescape.wiki/w/Bone_shortbow)
3.  [Bone staff](https://oldschool.runescape.wiki/w/Bone_staff)

For all 3 of them:
- [x] They add 10 damage to a players max hit (you can still miss and get a 0 though)
- [x] They can only be used against rats (meaning 0 dps/immune against all other monsters)

**Comment by jayktaylor** [comment]
The new weapons and mobs were added to the calc today, along with support for handling rat bone weapon immunity for non-rat monsters.

I'll leave adding the rest of the mechanics of the weapons (including the +10 max hit) to @LlemonDuck (or someone if they want to make a PR).

**Comment by SuperNerdEric** [comment]
@jayktaylor This copypasta comment is talking about "leaf-bladed" weapons when it should be rat bone

**Comment by SuperNerdEric** [comment]
With the bone mace I hit a 56 with 118 strength level, piety, and 126 strength on my gear. 

I've heard people with 130 strength on their gear can hit a 58.

**Comment by LlemonDuck** [comment]
I've added the bonus for melee and ranged in 2a6a31a159289387caadeebfe73dda41990efff5.

Need to determine the max hit formula for the staff, and also need some help researching the order of operations between inq and ratbane.

**Comment by LlemonDuck** [comment]
Bone staff max hit added in d38626399041b7cdd258a742f687a26b82e8fe4b

**Comment by LlemonDuck** [comment]
giant rat minion dist in 0d3b41f8678c3e4064d4b3536e3a741edfd1baea

Only thing remaining now is the inq order of operations

**Comment by LlemonDuck** [comment]
I found some inq and tested this, ratbane is applied first then inquisitor's second.

Strength level 99
Equipment strength 112
No prayers
Aggressive stance

I hit a max of 43, which lines up with the result when ratbane is applied first. If it were inquisitor's first, it would be a max of 42.
