### ISSUE TITLE
Scrolling through equipment selector can cause ratelimit issues

### ISSUE THREAD

**Issue by leejt** [weirdgloop/osrs-dps-calc#137]
### What went wrong?

If you scroll through the list of equipment fairly fast, some of the images will fail to load with a 429 error:
> You appear to be making a lot of async requests to the wiki[...]

While eventually we hope these will mostly be cached, we should probably exclude them (perhaps the entire subdomain) from the Cloudflare rate limiter.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

macOS

**Comment by jayktaylor** [comment]
Added `tools.runescape.wiki` as an exception to the CF rate limiting.
