### ISSUE TITLE
Custom named loadouts

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#146]
### What feature would you like to see?

I think it would be cool if you could name your loadouts something other than "Loadout 1" and have that custom loadout name show up on the graph. If you want to compare many sets of gear at once it would make it clearer at a glance.

I understand there are probably some UI concerns with variable length loadout names especially in the tabs and table, but even just the top text and on the tooltips on the graph would be helpful.

**Comment by LlemonDuck** [comment]
This was done a while ago but we missed closing this
