### ISSUE TITLE
other staffs are not included in magic dart leafy check

### ISSUE THREAD

**Issue by crab-pancake** [weirdgloop/osrs-dps-calc#149]
### What went wrong?

title (https://github.com/weirdgloop/osrs-dps-calc/blob/main/src/lib/CombatCalc.ts#L1392) adding condition for ` || selected spell == magic dart` would probably fix it

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Are you using `Slayer staff (e)` instead of the normal version? It doesn't seem to be accounted for in https://github.com/weirdgloop/osrs-dps-calc/blob/main/src/lib/CombatCalc.ts#L395

**Comment by crab-pancake** [comment]
ah that makes sense, i was using toxic staff of the dead. probably should add a few weapons to that check then
