### ISSUE TITLE
arclight specs reduce 5% of current stats instead of base?

### ISSUE THREAD

**Issue by crab-pancake** [weirdgloop/osrs-dps-calc#150]
### What went wrong?

putting in 20 arclight specs does not lower stats to 0

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
This matches what the wiki describes:
> Arclight retains Darklight's [special attack](https://oldschool.runescape.wiki/w/Special_attacks), Weaken, which consumes 50% of the player's special attack energy and lowers the opponent's [Strength](https://oldschool.runescape.wiki/w/Strength), [Attack](https://oldschool.runescape.wiki/w/Attack), and [Defence](https://oldschool.runescape.wiki/w/Defence) levels by 5% (10% for demons) of their current level + 1
