### ISSUE TITLE
Investigate saving shared loadouts in LocalStorage

### ISSUE THREAD

**Issue by leejt** [weirdgloop/osrs-dps-calc#185]
### What feature would you like to see?

Consider saving your generated loadouts in LocalStorage, as an alternative to actually keeping your active workspace around (basically the proposal from #7 )

Would be improved by #184 

Possibly a bad idea.

**Comment by MarcusOtter** [comment]
> Possibly a bad idea.

Why?

My suggestion is to always add loadouts to localstorage, and make this button remove it from localstorage.

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/35617441/259d47e8-d011-43cd-a5bd-2e49c650ad79)

Alternatively make loadouts transient by default and add a new "pin" button that keeps a loadout persistent in localstorage, and change it to "unpin" once it is pinned.
