### ISSUE TITLE
calc: monster immunities

### ISSUE THREAD

**Issue by LlemonDuck** [weirdgloop/osrs-dps-calc#20]
### Melee
- [ ] Kraken
- [ ] Abyssal portal
- [ ] TzKal-Zuk
- [ ] Jal-MejJak
- [ ] The Leviathan
- [ ] Avianses, except when using a salamander
- [ ] Dawn
- [ ] Olm mage hand and head (immune, not 1/3 dmg)
- [ ] Zulrah

### Ranged
- [ ] Tekton
- [ ] Kraken (1/7 dmg, min 1)
- [ ] Dusk
- [ ] Olm hands (1/3 dmg)
- [ ] Glowing crystal

### Magic
- [ ] Dusk
- [ ] Tekton (1/5 dmg, min 1)
- [ ] Glowing crystal (1/3 dmg)
- [ ] Olm head and melee hand (1/3 dmg)

### Weapon-Specific
- [ ] Guardians
- [ ] T3 Vampyres
    - Requires one of Ivandis' flail, Blisterwood sickle, or Blisterwood flail

**Comment by SuperNerdEric** [comment]
Not sure if this is about immune poison/venom/thrall/cannon

For posterity here's a list of monsters that I know are "immune" to melee
- Kraken
- Abyssal portal (CoX)
- TzKal-Zuk
- Jal-MejJak (Zuk healers)
- The Leviathan

**Comment by LlemonDuck** [comment]
Thanks! This is helpful. I'll start a checklist in the OP.

**Comment by crab-pancake** [comment]
melee:
- zulrah (immune)
- olm mage (right) hand and head (1/3 dmg?)
- dawn (immune)

range:
- vasa crystal
- olm both hands (1/3 dmg)
- dusk (immune)

mage:
- tekton (1/5 dmg)
- vasa crystal (1/3 dmg)
- olm melee (left) hand and head (1/3 dmg?)
- dusk (immune)

weapon specific:
- t3 vampyres (flail only)
- t2 vampyres (silver weapons or efaritay's aid)
- cox guardians (pickaxe only)

**Comment by SuperNerdEric** [comment]
Here's how Kraken damage reduction works: https://twitter.com/JagexAsh/status/1699360516488011950

**Comment by LlemonDuck** [comment]
Thanks for that. I've introduced a limiter that can be used for these in 70c45cf72ea1a40cfd1d7d5b954c4005789e4eb9, but it's not attached to any monsters yet.

**Comment by SuperNerdEric** [comment]
- [Leafy monsters](https://oldschool.runescape.wiki/w/Leafy_(attribute))
- Corporeal beast (50% damage except Corpbane, magic, and Ruby bolt specs)
