### ISSUE TITLE
calc: monster max hit limiters (zulrah, p1 verz, etc)

### ISSUE THREAD

**Issue by LlemonDuck** [weirdgloop/osrs-dps-calc#21]
- [ ] Fragment of Seren
    - "All damage towards her is capped at 24; if players would have dealt over 24 damage to her, it is reduced to 22-24 damage." Need to investigate whether this is `min(hit, randominc(2) + 22)` or `if hit >24, hit = randomic(2) + 22`.
- [ ] P1 Verzik
    - For any weapon that is not the dawnbringer, `hit = min(hit, randominc(10))`.
- [ ] Zulrah
    - max 50
- [ ] T2 Vampyres
    - Requires silver weaponry, unless using Efaritay's Aid, in which case max 10

**Comment by SuperNerdEric** [comment]
Just adding Fragment of Seren for posterity
