### ISSUE TITLE
manually set hp is reset to base when changing between loadouts

### ISSUE THREAD

**Issue by crab-pancake** [weirdgloop/osrs-dps-calc#215]
### What went wrong?

^^

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Likely a regression introduced in https://github.com/weirdgloop/osrs-dps-calc/commit/ec0d6b4ecac5e2813b299b71f3c549fcd760ffb5, will look into fixing it tomorrow.
