### ISSUE TITLE
TTK on Ruby bolts (e) and Vardorvis

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#236]
### What went wrong?

This Reddit post points out what I consider to be an actual bug.
https://www.reddit.com/r/2007scape/comments/1akj5nd/new_feature_on_osrs_wiki_dps_calc_damage_taken/kp90lzf/

Currently the TTK calculation uses the same damage distribution displayed in the results. However, for cases where your damage changes relative to monster health (Ruby bolts (e) and Vardorvis) that damage distribution is only true at the given HP you set in "Monster's Current HP". To accurately get the time to kill you would need to have a new damage distribution for each remaining HP of the monster (or at least when the distribution changes).

This link helps illustrate the problem. https://dps.osrs.wiki/?id=ContractBraceletSnakeweed 
If you leave Monster's Current HP at 750 HP it says TTK is 64.2s. 
If you change the Monster's Current HP to 500 HP it stays at 64.2s (expected).
If you change the Monster's Current HP to 400 HP it changes to 66.3s because it's now using your lower damage distribution.

https://github.com/weirdgloop/osrs-dps-calc/blob/staging/src/lib/PlayerVsNPCCalc.ts#L1057

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

### Any other information

Some more food for thought: This is a whole class of problems with the traditional way OSRS DPS calculators have handled Ruby bolt (e) procs and communicating what "DPS" actually means in this context. We currently calculate Ruby bolt (e) DPS based on "Monster's Current HP" which in itself is a little problematic as monsters don't stay the same health as you attack them. Of course you can change the "Monster's Current HP" to get the instantaneous DPS at any given health, **given the user understands what "DPS" is actually representing**.

Now this calculator is nicer in that it actually lets you graph Monster HP vs Player damage-per-second instead of having to keep fiddling with health numbers. Still (in my personal opinion) it might be good to have an asterisk with a tooltip explaining the nuance on the DPS in the results table and maybe even represent the DPS as a range [10.14 - 12.14].

**Comment by crab-pancake** [comment]
> If you leave Monster's Current HP at 750 HP it says TTK is 64.2s.
> If you change the Monster's Current HP to 500 HP it stays at 64.2s (expected).
> If you change the Monster's Current HP to 400 HP it changes to 66.3s because it's now using your lower damage distribution.

wait, why is that expected? that seems incorrect for several reasons

**Comment by SuperNerdEric** [comment]
> > If you leave Monster's Current HP at 750 HP it says TTK is 64.2s.
> 
> > If you change the Monster's Current HP to 500 HP it stays at 64.2s (expected).
> 
> > If you change the Monster's Current HP to 400 HP it changes to 66.3s because it's now using your lower damage distribution.
> 
> 
> 
> wait, why is that expected? that seems incorrect for several reasons
> 
> 
> 
> edit: looks like `this.monster.skills.hp` should be `this.monster.monsterCurrentHp`?
> 
> https://github.com/weirdgloop/osrs-dps-calc/blob/staging/src/lib/PlayerVsNPCCalc.ts#L1066

Hah, I think this is actually another problem with the way Monster HP / TTK is communicated in the calc. I assumed (not sure if rightly) it's intentional that the TTK always meant from the monster's total HP, not what you currently set.

**Comment by LlemonDuck** [comment]
This is an old issue now so I'm not sure what was implemented between this report and now, but I don't think this is an issue anymore. We calculate DPS + TTK on current HP, and the ttk dist accounts for variable-hp dps situations like ruby bolts and vardorvis by computing a new dist for each hp.

Gonna close but lmk if yall see anything that still needs fixing
