### ISSUE TITLE
change sorting of boosts to custom method

### ISSUE THREAD

**Issue by crab-pancake** [weirdgloop/osrs-dps-calc#245]
### What feature would you like to see?

proposed order: supercombat + range pot + saturated heart at the top, then salt/ovl, then individual supers + forgotten brew + imbued heart, then regular ovl and nmz super range/mage, then regular pots

**Comment by jayktaylor** [comment]
Order was reworked to place the more popular boosts first in https://github.com/weirdgloop/osrs-dps-calc/commit/51869a569a58d8ed93a5a475d35ea6dc3d49da3f
