### ISSUE TITLE
Max hit incorrectly calculated - Craw's bow slayer helm

### ISSUE THREAD

**Issue by Alfie94** [weirdgloop/osrs-dps-calc#272]
### What went wrong?

Incorrect max hit calculated with this loadout https://dps.osrs.wiki/?id=JusticiarValveTassets

Rigour and range pot active in game and max hit is 49 but the calculator shows 51.

Assuming there is something wrong with the formula with craw's bow and slayer helm buff.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jmyaeger** [comment]
Not sure where the craw's bow wiki page got the info, but it does say the craw's + slayer helm effect is additive rather than multiplicative (even though it's multiplicative with salve). This is also how DHCB + slayer helm is implemented, so there's at least some precedent here.
