### ISSUE TITLE
Selected style / spell is not being shared with "Share loadout" button

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#273]
### What went wrong?

When you share a loadout it resets your attack style to the default.

I chose the Jab (Crush, Aggressive) option here and when you share the loadout it reverts it back to Reap (Slash, Accurate).
https://dps.osrs.wiki/?id=AlchemistHeraldicFrom

I chose to Autocast Ice Barrage here and when you share the loadout it reverts back to Bash with the staff.
https://dps.osrs.wiki/?id=IvandisRainStrength

### What did you expect to happen?

Keep attack style when sharing loadouts.

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Should have been fixed with https://github.com/weirdgloop/osrs-dps-calc/commit/bcbce542c012765294e0e2bf94441df606ae81c6
