### ISSUE TITLE
New Armour Stat (Perils of Moon max hits)

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#274]
### What went wrong?

When attacking the Perils of Moon bosses you have nonstandard max hits. It's not currently understood the exact mechanics, but there's a lot of theorycrafting going on in this Reddit thread.

https://www.reddit.com/r/2007scape/comments/1bkl0km/perilous_moons_bosses_have_a_weird/

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by jmyaeger** [comment]
This appears to be related to the new "Armour" stat shown in Monster Examine. [This screenshot](https://media.discordapp.net/attachments/269673599554551808/1220404983887826944/image.png?ex=660ed1b6&is=65fc5cb6&hm=42bb5956fe73bf66368de0fbfa4a8c968b3c0ff2c8254c02aeffd291506b6450&) indicates that the Armour stat reduces damage by the amount shown. 

Monster Examines of the three bosses show values of 4 for Eclipse Moon, -2 for Blood Moon, and -5 for Blue Moon. Note that the screenshot says -5 would indicate 5 damage reduced, but I think it's actually the opposite—it reduces damage by -5 (i.e., boosts it by 5). These line up well with in-game observations of damage, although there seems to be some mechanic or part of the Eclipse fight where the damage is reduced by less than 4. 

The damage boost or reduction appears to be applied post-roll to each hitsplat of a weapon. For example, a scythe in max melee hits 50-25-12 max normally, but it hits a max of 55-30-17 on Blue Moon. 

There are probably still a few details and edge cases worth testing, but this seems to explain most if not all of what's being observed.

**Comment by LlemonDuck** [comment]
Closed by #350
