### ISSUE TITLE
Dual macuahuitl is not implemented

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#277]
### What went wrong?

https://oldschool.runescape.wiki/w/Dual_macuahuitl

From the Wiki - there may be some nuances here that aren't completely accurate, maybe needs some more research.

Uniquely, the weapon hits twice per attack, dealing damage in two [hitsplats](https://oldschool.runescape.wiki/w/Hitsplats) spaced 1 game tick apart. The second hit also has a lower accuracy than the first. Upon attacking, there are two accuracy checks. If the first check fails, the player will hit two zeroes. If it succeeds, the game will roll damage for the first hit, then roll a second accuracy check for the second hit. As a result, "half" of the player's dps functions normally, while the other "half" is reduced due to needing to pass two accuracy checks.

When worn with all of the other pieces of the blood moon armour set, the player gains the Bloodrager set effect, where the dual macuahuitl has a 33% chance to apply an attack cooldown one tick smaller than usual upon a successful hit, allowing the player to attack again after 3 ticks. Both hits count towards this independently, meaning there is a 55% chance to gain the effect if both hits are successful. 

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by jmyaeger** [comment]
What aspects of this do you think might be inaccurate? I have done a lot of testing, and the description there looks accurate to me, albeit clumsily worded in some places.

**Comment by jayktaylor** [comment]
Implemented in https://github.com/weirdgloop/osrs-dps-calc/commit/6afd900ccfae862ffa1ba1c69dbb5b80c7a246cc

**Comment by jmyaeger** [comment]
FYI the staged implementation is currently using the full max hit for each of the two hits rather than splitting it between the two hits.

**Comment by jayktaylor** [comment]
Fixed shortly after deployment - thanks for raising this
