### ISSUE TITLE
Loadout comparison graph causes high CPU usage when idle

### ISSUE THREAD

**Issue by vaisest** [weirdgloop/osrs-dps-calc#287]
### What went wrong?

It seems that LoadoutComparison keeps constantly rerendering even though nothing is being changed. This causes high CPU usage whenever the comparison is shown.

The console is also spammed with massive amounts of debug messages.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Other

**Comment by jayktaylor** [comment]
Thanks for the report! This seems to be because `toJS(store.monster)` was *technically* creating a different JavaScript representation of an object. Converting it to a string instead using `JSON.stringify(store.monster)` seems to have fixed this.
