### ISSUE TITLE
Full ahrim’s + amulet of the damned is overwriting hit dists

### ISSUE THREAD

**Issue by jmyaeger** [weirdgloop/osrs-dps-calc#301]
### What went wrong?

When wearing a full Ahrim’s set with an amulet of the damned, enabling sunfire runes or equipping a tome of fire or water (with a relevant spell selected for each) does not affect the hit distributions or max hits. Removing the amulet of the damned results in the intended hit distributions.

### What did you expect to happen?

The effects should be stackable.

### What browsers are you seeing the problem on?

Safari

### What device(s) are you seeing the problem on?

iOS

### Any other information

It looks to me like the Ahrim’s effect (which is applied after the tome and sunfire effects) is creating a new distribution based on the original one that doesn’t include the tomes and sunfire:

```
if (this.player.style.type === 'magic' && this.isWearingAhrims()) {
      dist = new AttackDistribution([
        new HitDistribution([
          ...standardHitDist.scaleProbability(0.75).hits,
          ...standardHitDist.scaleProbability(0.25).scaleDamage(13, 10).hits,
        ]),
      ]);
    }
 ```

Also, re: how the tome and Ahrim’s effects should stack, it appears based on in-game observations that the tome has been reworked to apply its boost pre-roll rather than post-roll, most likely in preparation for the upcoming elemental weaknesses rework. I confirmed that the beta world tome of fire is a pre-roll boost, and I have main game data from a tome of fire with seared pages where there were no gaps in the hit distribution.

**Comment by LlemonDuck** [comment]
In an explicit conversation with Jagex wrt to the defence rework changes, they specified that the Tome of fire was not changing where/how it's computed. Do you have some evidence (tracked hits?) I can point to?

I don't think we're aware yet of how the sunfire runes combine with Ahrim's / Tome of fire. I'll put an open call in the discord to see if anyone can find a way to tell.
