### ISSUE TITLE
Charge not impacting God Spell Max hit

### ISSUE THREAD

**Issue by Grizzlea** [weirdgloop/osrs-dps-calc#303]
### What went wrong?

Playing aroudn with Claws of Guthix using autocast from Void Knight Mace, and when selecting the "Using the Charge Spell" I don't get the relevant max hit increase.

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/166742492/30b94018-a13b-465c-b317-6cfe72d77dbe)

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Hey @Grizzlea thanks for reporting this. It's hard to tell from your screenshot whether you're wearing one or not, but you only get the extra boost while using Charge if you're wearing an appropriate god cape (in this case, Guthix). From the void knight mace page:

> While Claws of Guthix can be cast and autocast while wearing an [imbued saradomin cape](https://oldschool.runescape.wiki/w/Imbued_saradomin_cape) or [imbued zamorak cape](https://oldschool.runescape.wiki/w/Imbued_zamorak_cape), an appropriate cape ([guthix cape](https://oldschool.runescape.wiki/w/Guthix_cape) or its [imbued](https://oldschool.runescape.wiki/w/Imbued_guthix_cape) variant) must still be worn to receive the damage boost from [Charge](https://oldschool.runescape.wiki/w/Charge).

If you're wearing a Guthix-affiliated cape in this setup and still not getting the boost, please share a link (button at the top right of the calc page) and I'll re-open the issue!
