### ISSUE TITLE
RuneLite integration

### ISSUE THREAD

**Issue by LlemonDuck** [weirdgloop/osrs-dps-calc#32]
In the future, create a RuneLite integration that allows players to open their current equipment set in the DPS calculator in their browser.

**Comment by jayktaylor** [comment]
Core RuneLite integration implemented in https://github.com/runelite/runelite/commit/e3da777aa66df3e9e8dd9dc79e4de4bb6c075a4f which allows users to click a "View DPS" button on their equipment stats UI to open the DPS calc with their current gear setup.
