### ISSUE TITLE
Cannot visually compare gear the way excel could.

### ISSUE THREAD

**Issue by JZomDev** [weirdgloop/osrs-dps-calc#325]
### What feature would you like to see?

Duke Sucellus' Strategies has this notes on the gear selection. (Specifically b)

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/14265490/c82fefac-0ec4-4419-aea2-92b42d1af76d)

The imgur link is https://imgur.com/a/ci8TaP4 which takes you to the dps excel spreadsheet of the comparison

Trying to rebuild the same in wiki's dps calc I cannot demonstrate that the two graphs/stats are equal due to no change in max hit, because I can only show one tab of gear at a time && cannot show the prayers/potions used unless I want to do many screenshots compared to excel's single screenshot.

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/14265490/5f287ef2-439d-46c8-8fc6-5b6939d2eb82)

**Comment by jayktaylor** [comment]
Hey - what would you hope is the solution here? I understand that it's a little harder to visually see multiple loadouts side by side, but the UI is intended to be easier to understand and use than the spreadsheet equivalents, so that there's less barrier to entry for more casual players.

I'm going to close this for now because I'm not really sure there's a "fix" to this.

**Comment by JZomDev** [comment]
A fix could be that you’re got a more cluttered/dense information view because having to screen shot 4 tabs isn’t it, it’s like people who don’t play the game or used the old sheet made this one. It’s meant to replace the sheet, so being able to do what it did would be nice. On May 29, 2024, at 1:43 PM, Jayden ***@***.***> wrote:﻿
Hey - what would you hope is the solution here? I understand that it's a little harder to visually see multiple loadouts side by side, but the UI is intended to be easier to understand and use than the spreadsheet equivalents, so that there's less barrier to entry for more casual players.
I'm going to close this for now because I'm not really sure there's a "fix" to this.

**Comment by JZomDev** [comment]
It should have a dense/advanced mode or what ever would be the equal to what this is meant to replace. 

Having 4 tabs to show what could be seen in a summary isn't it.
