### ISSUE TITLE
Nightmare Totem Magic Damage Doubling

### ISSUE THREAD

**Issue by RonnyTommy548** [weirdgloop/osrs-dps-calc#345]
### What went wrong?

With a magic gear setup, the damage isn't getting doubled vs. nightmare/pnm totem

### What did you expect to happen?

The damage was showing what the shadow would hit regularly, not the doubled damage

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
Closed by #352 and #353
