### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by EIKOOT** [weirdgloop/osrs-dps-calc#346]
### What feature would you like to see?

Here is a list of features I really miss from dps tool 
1. special attack max hit
2. special attack accuracy
3. expected damage (weapon attack speed * dps)
4. special attack expected damage (weapon attack speed * special attack dps) 
5. allow weapon attack speed modifications. For example, p2 verzik scythe dps, speed should be 5.3t instead of 5t as 5t scything is not possible.
6. allow monster hp modifications. Monsters have multiple phases and often I am more interested in single phase TTK graph rather than whole boss health.
7. remove 0s from TTK graph

Some of these could be a toggle and off by default, so it wouldn't be a table with 20 rows.
Info such as attack roll and defence roll does not provide any insight (could be off disabled by default)

**Comment by jayktaylor** [comment]
Special attacks are planned in #141, and you can click "Enable manual mode" on the right side of the footer to be able to edit monster HP (though it's an experimental mode).
