### ISSUE TITLE
TOA Option for Tumeken's shadow

### ISSUE THREAD

**Issue by EnuDelrum** [weirdgloop/osrs-dps-calc#368]
### What feature would you like to see?

After equiping the Tumeken's shadow, display an option for toggling on TOA. This would multiply the magic damage by x4 instead of the default x3 outside of TOA (up to a 100% bonus).
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/128336524/c4248bee-4dbd-4f1b-8ebe-d040b01f216f)

Here's an example of Flames of Zamorak giving you the option for Charge after being selected.
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/128336524/1bed19fa-480c-4991-93b3-a8e2efe9e5b3)

### Evidence

https://oldschool.runescape.wiki/w/Tumeken%27s_shadow#Passive_effect

> Tumeken's shadow has a [passive effect](https://oldschool.runescape.wiki/w/Passive_effect) exclusive to its built-in spell, in which the player's magic attack bonus and [magic damage](https://oldschool.runescape.wiki/w/Magic_damage) are multiplied by three from the player's worn equipment (four within the Tombs of Amascut); the magic damage increase from this is capped at a total of 100% Magic Strength. This effect also applies with negative bonuses, tripling the negative bonus.

**Comment by Defiect** [comment]
Setting the NPC target to any ToA one already accounts for this passive change

**Comment by EnuDelrum** [comment]
> Setting the NPC target to any ToA one already accounts for this passive change

I should have realized this. Thank you!
