### ISSUE TITLE
dual wield + flat armor

### ISSUE THREAD

**Issue by rdmqwerty** [weirdgloop/osrs-dps-calc#381]
### What went wrong?

i think the dps calculator logic is incorrect in regards to dual wield weapons vs enemies with a flat armor reduction

### What did you expect to happen?

i would expect dual wielding weapons to have a higher dps against enemies with flat armor reduction such as Sulphur Nagua

### What browsers are you seeing the problem on?

Other

### What device(s) are you seeing the problem on?

Other

### Any other information

i setup 2 stat-identical loadouts here - https://dps.osrs.wiki?id=ButterMahoganyImplement

loadout 1 has dragon scimitar. loadout 2 has sulpher blades. i added a warrior helm to loadout 1 and climbing boots to loadout 2 in order to make the accuracy and strength stats completely identical. and the dps outputs for both loadouts are identical according to the current calculations. however, in practice, the sulpher blades will perform way better because of their dual wielding properties and causing 2 instances of damage per attack. this leads me to believe that there is an error in the calculations for dual wielding weapons

**Comment by jmyaeger** [comment]
This is because the sulphur blades are not currently implemented as a double-hitting weapon in the calc. #382 should fix that, if it gets merged.

**Comment by LlemonDuck** [comment]
Closed by 8082e306162dd8e8edd974519f5b88a3ddf3372e
