### ISSUE TITLE
Scorching bow issues (special attack)

### ISSUE THREAD

**Issue by RonnyTommy548** [weirdgloop/osrs-dps-calc#442]
### What went wrong?

~~The scorching bow special attack is described as "Scorching shackles increases accuracy by 30%" on wiki. Despite that, on wiki dps I'm seeing exactly same accuracy under special attack section.~~ (appeared to just be wrong information on wiki page)

The special attack max hit should be +5 higher than regular hit, not +10, since only 5 ticks of 1 burn. https://dps.osrs.wiki?id=IcosahedronJadeScribbled

Also as you folks are probably already aware the max hit of the regular attack w/ slayer helm in the mix is calculated wrong vs. what's in game right now, but Jagex might patch it so can wait and see about that aspect.

### What did you expect to happen?

~~The accuracy of the special attack should be increased~~
The max hit should be +5 higher than regular hit not +10 (Orion suggested maybe its using 10 burning ticks like bone claws)

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jmyaeger** [comment]
@LlemonDuck I think it's just double counting the extra damage here. The extra damage is included in the spec hit dist, but `getDotExpected()` is also adding it in, resulting in +10 on the spec max instead of +5.
