### ISSUE TITLE
Araxyte slayer helm not counting for slayer task

### ISSUE THREAD

**Issue by Antoine-dh** [weirdgloop/osrs-dps-calc#469]
### What went wrong?

It is the only slayer helm recolor displayed in the list and also doesn't apply task damage boost

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by Antoine-dh** [comment]
Do not have time to PR but I believe is fixed by adding it to this regex
https://github.com/weirdgloop/osrs-dps-calc/blob/9ff475c1b90a0d207597b2ed9defcaf7927e839d/scripts/generateEquipmentAliases.py#L119

**Comment by cloud-aspect** [comment]
Bump, posted this in the Discord channel, was about to post my own git issue but I see there already is one here

**Comment by LlemonDuck** [comment]
This should be fixed and released now via ac3b179b3eeebe7aab79067a6d4212a906269fa8
