### ISSUE TITLE
Twisted bow calculation incorrect

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#47]
### What went wrong?

The Twisted bow is giving the same max hit (very high) no matter which monster I choose

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/9d6353c3-7146-49ef-ab86-a8ed12714eb9)

Also the accuracy seems incorrect compared to the DPS sheet.

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/a039de37-690a-4770-ba1f-8574a844cb5d)

### What did you expect to happen?

Max hit should change depending on targets magic level / magic accuracy
Accuracy should match DPS sheet

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

### Any other information

I haven't dug into exactly what's going on but I don't think you can use the caret (^) operator [here](https://github.com/weirdgloop/osrs-dps-calc/blob/main/src/lib/CombatCalc.ts#L451), which in JavaScript is the bitwise XOR operator, not the exponentiation operator.

`let tbowMod = Math.trunc(Math.min(140, (140 + (m*10-10)/100 - (m-100)^2/100)));`

Here's how I wrote it in my project:

```function twistedBowStrengthMultiplier(targetMagic: number, raid: Raid): number {
    // The Magic level or accuracy caps at 250 outside the Chambers of Xeric, and 350 within.
    if (targetMagic > 350 && raid === Raid.ChambersOfXeric) {
        targetMagic = 350;
    } else if (targetMagic > 250) {
        targetMagic = 250;
    }

    let damageMultiplier = 250 + Math.floor((3 * targetMagic - 14) / 100) - Math.floor(Math.pow(3 * targetMagic / 10 - 140, 2) / 100);
    if (damageMultiplier > 250) {
        damageMultiplier = 250;
    }
    return damageMultiplier / 100;
}

function twistedBowAccuracyMultiplier(targetMagic: number, raid: Raid): number {
    // The Magic level or accuracy caps at 250 outside the Chambers of Xeric, and 350 within.
    if (targetMagic > 350 && raid === Raid.ChambersOfXeric) {
        targetMagic = 350;
    } else if (targetMagic > 250) {
        targetMagic = 250;
    }

    let accuracyMultiplier = 140 + Math.floor((3 * targetMagic - 10) / 100) - Math.floor(Math.pow(3 * targetMagic / 10 - 100, 2) / 100);
    if (accuracyMultiplier > 140) {
        accuracyMultiplier = 140;
    }
    return accuracyMultiplier / 100;
}

**Comment by LlemonDuck** [comment]
closed by ae582ae
