### ISSUE TITLE
Inaccurate fang max hit and accuracy calculation

### ISSUE THREAD

**Issue by jmyaeger** [weirdgloop/osrs-dps-calc#48]
### What went wrong?

The accuracy and max hit calculations for Osmumten's fang do not line up with expected values (from the Bitterkoekje DPS calculator).

### What did you expect to happen?

The max hit is currently calculated by multiplying its true max hit by 17/20, but (based on the Bitterkoekje DPS calc) it should instead be first finding the minimum hit (3/20 * true_max_hit), truncating that, and subtracting it from true_max_hit to get the max hit. 

The hit chance formulas are also incorrect at the moment. If we trust the Bitterkoekje sheet. the hit chance formulas need to be swapped for inside/outside ToA (i.e., it's currently using the outside-of-ToA formula against monsters in ToA, and vice versa).

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
@jmyaeger do you have any empirical evidence on the fang max being `max - trunc(3/20 * max)`, or just the bitterkoekje sheet?

Accuracy is fixed in fa32f44d

**Comment by jmyaeger** [comment]
This is from the ToA rewards blog (https://secure.runescape.com/m=news/tombs-of-amascut-raid-rewards-v2?oldschool=1):

"We’re doing something a bit different with the Fang, so let’s look at how the damage will be calculated. Instead of rolling ‘0-max’ hit like most weapons, it will instead:


Roll ‘(max hit * 0.15) - (max hit - (max hit * 0.15))’
For example: If the max hit is 60, then it would roll between 9-51."

I haven't tested it myself, but I couldn't find anything in subsequent blogs about changing that calculation.

**Comment by LlemonDuck** [comment]
Thanks, that sounds good enough to me.
