### ISSUE TITLE
Huey Missing Dragon Attribute

### ISSUE THREAD

**Issue by RonnyTommy548** [weirdgloop/osrs-dps-calc#496]
### What went wrong?

All 3 huey-related NPCs, including the huey head, tail and body, are missing the dragon attribute

### What did you expect to happen?

These NPCs should have the dragon attribute

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
fixed in #501
