### ISSUE TITLE
Huey Tail Hit Distribution w/ Dual Macuahuitl

### ISSUE THREAD

**Issue by RonnyTommy548** [weirdgloop/osrs-dps-calc#497]
### What went wrong?

https://dps.osrs.wiki?id=HoneyWoollyPath

The hit distribution is definitely wrong because hitting 2 total damage (2x 1 hitsplats) is very common. In-game, I believe missed hits are converted from 0->1 when you have a crush dominant set. I recorded some hits and my claim is reflected in this distribution:

![Figure_1](https://github.com/user-attachments/assets/7b960bab-a225-4586-b4fc-ed19e0ef88d5)

Wiki DPS shows:

![image](https://github.com/user-attachments/assets/6418c6cc-7778-407e-b8c7-5ce833b9cb7e)

Also this is showing that hitting 0 or 1 is possible, but those are not possible. You can never hit a 0 hitsplat when crush is your dominant attack bonus I believe

### What did you expect to happen?

I expected the hit distribution of the dual macs on huey tail to reflect the fact that 1, 1 is very common. I also expected 0 and 1 damage to be absent from the hit distirbution

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
fixed in #511
