### ISSUE TITLE
Tome of Earth/Slayer Helm/Dragon hunter wand

### ISSUE THREAD

**Issue by Aerosplice** [weirdgloop/osrs-dps-calc#498]
### What went wrong?

Tome of earth doesn't work in calculator, had to manually replace earth weakness with fire weakness and use tome of fire to get accurate number

### What did you expect to happen?

I expect the damage to be about 10% HIGHER  when using tome of earth using earth spell
When selecting on slayer task the dps number doesnt change https://dps.osrs.wiki?id=GuamTzrekHarrys
only when using the dragon hunter wand

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by LlemonDuck** [comment]
fixed in #499
