### ISSUE TITLE
Hit distribution is not useful when npc hp is lower than players max hit

### ISSUE THREAD

**Issue by EIKOOT** [weirdgloop/osrs-dps-calc#508]
### What feature would you like to see?

If npc hp is 8 and weapon rolls from 1 to 10incl (say each roll has 10% chance)
It would be more useful to see rolls 8, 9 and 8 aggregated into 1 roll of 8 damage which would have 30% chance in the hit distribution graph.

**Comment by LlemonDuck** [comment]
This was originally used, but deemed not as useful as other showing the full distribution for non-standard weapons. You may find the TTK distribution is more useful here regardless, as it will show you % odds of kill vs no-kill over time periods?
