### ISSUE TITLE
Remove multiple entries for Perilous Moon Gear

### ISSUE THREAD

**Issue by ryanab00** [weirdgloop/osrs-dps-calc#540]
### What feature would you like to see?

Currently. New/Used moons gear brings up multiple entries, when in reality it should just be 3 like any other gear set.
Removing the #new/used would clean up the gear list and make it easier to find the item you actually want.
Additionally, I think #undamaged should be removed from barrows equipment as that's already the standard and just takes up unneeded space.

### Evidence

![image](https://github.com/user-attachments/assets/032de1f9-dcf9-4b05-beb3-58533613d2d7)
![image](https://github.com/user-attachments/assets/923d1db9-da3a-4d58-b2fe-24c9a1f4c29a)

**Comment by LlemonDuck** [comment]
done in #541
