### ISSUE TITLE
Incorrect max hit for obsidian weapon + armor

### ISSUE THREAD

**Issue by jmyaeger** [weirdgloop/osrs-dps-calc#56]
### What went wrong?

When testing an obby sword (Toktz-xil-ak) with full obby armor (no berserker necklace), the max hit I got was 4.

### What did you expect to happen?

The max hit in the setup I was using should be 47.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

### Any other information

It looks like the max_hit calculation is missing a " * 11"—right now it's just baseDmg / 10 instead of baseDmg * 11 / 10.

**Comment by LlemonDuck** [comment]
I've fixed the mentioned typo in ae4c34de, but I'm only seeing a max hit of 45.

Once the site updates can you let me know if this matches the setup you were using: https://dps.osrs.wiki/?id=1aa8d4f1-30e2-4fe7-9769-bec6e04d77da?

**Comment by jmyaeger** [comment]
That setup has the dagger (Toktz-xil-ek); I was testing the sword (Toktz-xil-ak). I'm now getting 47 with that setup and the sword

**Comment by LlemonDuck** [comment]
Nice, thanks!
