### ISSUE TITLE
Preset Loadouts

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#62]
### What feature would you like to see?

The Bitterkoekje sheet offers some preset loadouts such as max melee, range, mage, void, Dharok's, etc to make it easier to do a quick DPS check. It would be nice to have something similar.

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/7608429/61c51838-1168-4c27-a15b-b7c3c5593715)

**Comment by jayktaylor** [comment]
Sounds like a good idea. Not sure about the UI/UX for this though. Maybe a dropdown placed under the equipment select combobox that has a list of these presets to choose from?

**Comment by Nightfirecat** [comment]
Maybe something like the RuneLite site's download button, but in `<input> + <button>` format
![Screenshot_20240111_224123](https://github.com/weirdgloop/osrs-dps-calc/assets/2199511/e2c91e04-7825-470e-89c1-202ab4eee8a3)

eg.
<pre>
╭─────────────────────────────────┬───────────╮
│ Search for equipment to wear... │ Presets ▼ │
╰─────────────────────────────────┴───────────╯
</pre>
