### ISSUE TITLE
magic def of verzik and ice demon not correct

### ISSUE THREAD

**Issue by LootBagger** [weirdgloop/osrs-dps-calc#64]
### What went wrong?

Accuracy of magic on p2 verzik in (almost) max mage is much lower than it should be. The accuracy of magic on verzik is based on her def level not her magic level. This calculator assumes her def works the way every other monster in the game works.

### What did you expect to happen?

Accuracy in this setup https://dps.osrs.wiki/?id=4a1f521e-7a9b-4756-93a1-c38859b3b63c should be around 83% not 65%.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

### Any other information

Ice demon also calculates magic def this way I think.

**Comment by LlemonDuck** [comment]
closed by #59
