### ISSUE TITLE
Vardorvis defense not calculating correctly

### ISSUE THREAD

**Issue by keithrobichaud** [weirdgloop/osrs-dps-calc#66]
### What went wrong?

Vardorvis shows as 0 def.

![image](https://github.com/weirdgloop/osrs-dps-calc/assets/10227040/0bc0c691-6717-45ca-bdcb-053f326bb0f3)

### What did you expect to happen?

As far as I'm aware, his defense is supposed to scale downwards with his HP.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Seems like this is because the wiki page doesn't explicitly give the monster a hard HP value (which makes sense).

We will likely have to add some special handling to the Python script we use to grab the wiki data to deal with this case, to ensure that it has a base HP value.

**Comment by LlemonDuck** [comment]
closed by b59631bb235a8d9d3b76e6cb235a543441ea231e
