### ISSUE TITLE
Make Monster.id nonnull

### ISSUE THREAD

**Issue by Nightfirecat** [weirdgloop/osrs-dps-calc#70]
### What feature would you like to see?

Remove the option for a monster to have null id; it doesn't really make sense for a monster to not have an ID. This seems like it may have been added while TOA was initially being supported.

For possible edge-case scenarios in the future, I recommend using `-1` as a default [instead of `null` that's used now](https://github.com/weirdgloop/osrs-dps-calc/blob/f705dd355d406caa784eec24cf160c7dceb1de1c/src/app/components/monster/MonsterSelect.tsx#L26), as it'll improve the development experience by making it possible to replace the `this.monster.id || 0` uses in CombatCalc.

**Comment by jayktaylor** [comment]
I think I agree with making it non-nullable. After the changes made in https://github.com/weirdgloop/osrs-dps-calc/commit/d5bd38812b486a51b09d8e6751af137bc80a389b and https://github.com/weirdgloop/osrs-dps-calc/commit/a2c4262799b00960f47db7945c62321396063536, there should be no scenario where a monster has no ID.
