### ISSUE TITLE
regression: ensure that select/combobox lists only take up required height

### ISSUE THREAD

**Issue by jayktaylor** [weirdgloop/osrs-dps-calc#75]
### What went wrong?

Regression introduced in https://github.com/weirdgloop/osrs-dps-calc/commit/1d6aa43cc6084aa3e2629b0e1934181a829455c4.

<img width="378" alt="Screenshot 2024-01-13 at 19 00 18" src="https://github.com/weirdgloop/osrs-dps-calc/assets/7265189/301d5978-4ece-4227-8995-da9d2bf76168">

### What did you expect to happen?

When there are only a small number of items in a select dropdown list, the height of the list container should only be the required height to fit the content.

### What browsers are you seeing the problem on?

Firefox

### What device(s) are you seeing the problem on?

Windows

**Comment by Nightfirecat** [comment]
I'm having a hard time with this, but it seems like removing some amount of `position: absolute;` in the tree of elements that make up the dropdown, and applying some amount of `width: fit-content;` and/or `width: max-content;` seems to fix it. I don't know how that'd work with the couple of intermediate elements between `<Virtuoso>` and the list item elements though--nor do I know for sure this would work for longer lists of items.
