### ISSUE TITLE
Zogre / Skogre and Ogre bow / Comp ogre Bow

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#86]
### What feature would you like to see?

From the wiki:

[Skogres ](https://oldschool.runescape.wiki/w/Skogre) are almost immune to normal weapons (you will sometimes still hit, but for very low damage). Brutal arrows are effective against them, as is the Crumble Undead spell (however, damage is halved, for a maximum of 7). 

[Zogres ](https://oldschool.runescape.wiki/w/Zogre) are almost immune to normal weapons (you will hit just as often, but damage is reduced by 80%, a halberd of any kind is recommended to strike from distance), brutal arrows are effective against them, as is the Crumble Undead spell (damage is halved, for a maximum of 7). Also, poison works full power, so p++ weapons might be good against them. 

[Ogre bow](https://oldschool.runescape.wiki/w/Ogre_bow) The Void Knight equipment set's accuracy bonuses do stack with the Ogre bow, however, the damage bonus does not get applied.
[Comp ogre bow](https://oldschool.runescape.wiki/w/Comp_ogre_bow) The Void Knight equipment set's accuracy bonuses do stack with the Ogre bow, however, the damage bonus does not get applied.

https://twitter.com/JagexAsh/status/1169527067358183424

**Comment by LlemonDuck** [comment]
>  (you will sometimes still hit, but for very low damage)

Do we have a formula on this?

**Comment by SuperNerdEric** [comment]
> Do we have a formula on this?

No idea, I just sent Mod Ash a tweet so I guess we will see if he responds. https://twitter.com/PiesMillion/status/1746318208179523684

**Comment by SuperNerdEric** [comment]
I asked again and got some more information https://twitter.com/JagexAsh/status/1747570723487461880
