### ISSUE TITLE
Fire Warrior of Lesarkus / Ice Arrows

### ISSUE THREAD

**Issue by SuperNerdEric** [weirdgloop/osrs-dps-calc#87]
### What feature would you like to see?

https://oldschool.runescape.wiki/w/Ice_arrows

[Lesarkus](https://oldschool.runescape.wiki/w/Fire_Warrior_of_Lesarkus) is immune to all ammunition except ice arrows and cannonballs.

**Comment by LlemonDuck** [comment]
This is true about Lesarkus, not Fareed. But Fareed has his own slight immunity, so I'm moving that into #90.
