### ISSUE TITLE
Recolored slayer helmets do not apply boosts

### ISSUE THREAD

**Issue by jmyaeger** [weirdgloop/osrs-dps-calc#91]
### What went wrong?

When equipping a recolored slayer helmet (black, green, hydra, etc.), the damage and accuracy boosts are not applied. With the same setup, a normal slayer helmet does apply the proper accuracy and damage boosts.

### What did you expect to happen?

All slayer helmets should behave the same way, or else the recolored ones should be removed from the item list.

### What browsers are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on?

Windows

**Comment by jayktaylor** [comment]
Thanks for the issue! Recoloured slayer helmets will be removed from the list as part of #39.
